# # Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# version: 2.1
# # Use a package of configuration called an orb.
# orbs:
#   # Declare a dependency on the welcome-orb
#   welcome: circleci/welcome-orb@0.4.1
# # Orchestrate or schedule a set of jobs
# workflows:
#   # Name the workflow "welcome"
#   welcome:
#     # Run the welcome/run job in its own container
#     jobs:
#       - welcome/run

# dependencies:
#   pre:
#     - go get github.com/tcnksm/ghr

# compile:
#   override:
#     - ant package

# deployment:
#   release:
#     tag: /(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)/
#     commands:
#       - ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` output/

# version: 2.1
# workflows:
#   main:
#     jobs:
#       - build
# jobs:
#   build:
#     machine:
#       image: windows-server-2019-nvidia:stable
#       docker_layer_caching: true    # default - false

# version: 2.1

# orbs:
#   win: circleci/windows@2.3.0

# jobs:
#   build:
#     executor: win/default
#     steps:
#       - checkout
#       - run: echo 'Hello, Windows'



version: 2.1
orbs:
  github-release: h-matsuo/github-release@0.1.1
jobs:
  build:
    description: Create dummy file and publish a new release tagged `vX.Y.Z`.
    executor: github-release/default
    steps:
      - run:
          command: |
            mkdir artifacts
            echo dummy > ./artifacts/file
      - github-release/create:
          tag: vX.YY.ZZ
          title: Version vX.YY.ZZ
          description: This release is version vX.YY.ZZ .
          file-path: ./artifacts/file
          pre-release: true
          title: "Deployed pre-release"
#       - run:
#           command: |
#             github-release release \
#               --security-token << parameters.github-token-variable >> \
#               --user << parameters.user >> \
#               --repo << parameters.repository >> \
#               --tag << parameters.tag >> \
#               --name "<< parameters.title >>" \
#               --description "<< parameters.description >>" \
#               --target << parameters.target >> \
#               <<# parameters.draft >> --draft <</ parameters.draft >> \
#               <<# parameters.pre-release >> --pre-release <</ parameters.pre-release >>




